### ISSUE TITLE
Open Spots (Open Source version of this app)

### ISSUE THREAD

**Issue by jaypyles** [notAkki/spots#3]
If anyone wants to use this, I have developed a fork of this called Open Spots, that lets you deliver your own data to visualize. Ours is deployed on Vercel, but its also available as a Docker image on Dockerhub, so you can host it yourself if you would like (given that you have an API setup).

Here's a link to the deployment and the github repo: 
https://open-spots.vercel.app/
https://github.com/jaypyles/open-spots

**Comment by notAkki** [comment]
This is awesome! I'm glad you found my project worth using and I want to thank you for making it easier for others to build with it as well!
